### ISSUE TITLE
Potential inconsistency in User Manual for uservp routine 

### ISSUE THREAD

**Issue by lcarasik** [Nek5000/Nek5000#32]
In the user manual, 
![udiff_utrans](https://cloud.githubusercontent.com/assets/19592378/16928898/bf859280-4cfa-11e6-845b-9714d61088f9.png)
it states that the udiff is the term for density (or rho*cp, etc) and utrans is the term for viscosity (visc, thermal conductivity, etc). This is counter to what has been stated in this nek5000 user post: http://lists.mcs.anl.gov/pipermail/nek5000-users/2014-December/003146.html

"utrans and udiff are the transport and diffusion coefficients, respectively, in a particular advection-diffusion equation. " Which implies the udiff and utrans are flipped in the user manual.

Can this be clarified?

**Comment by emerzari** [comment]
Good catch. The manual is wrong.

On Jul 18, 2016, at 3:34 PM, Lane Carasik <notifications@github.com<mailto:notifications@github.com>> wrote:

In the user manual,
[udiff_utrans]https://cloud.githubusercontent.com/assets/19592378/16928898/bf859280-4cfa-11e6-845b-9714d61088f9.png
it states that the udiff is the term for density (or rho*cp, etc) and utrans is the term for viscosity (visc, thermal conductivity, etc). This is counter to what has been stated in this nek5000 user post: http://lists.mcs.anl.gov/pipermail/nek5000-users/2014-December/003146.html

"utrans and udiff are the transport and diffusion coefficients, respectively, in a particular advection-diffusion equation. " Which implies the udiff and utrans are flipped in the user manual.

Can this be clarified?

**Comment by oanaoana** [comment]
Yes I know.. been panning to fix it for ages. Just things were moving about and didn't get to it.

**Comment by lcarasik** [comment]
Ah ok, I would suggest leaving this open until it is resolved. That way, an easily searchable item for users can be found. Just thoughts.

**Comment by lcarasik** [comment]
Can this be reopened? It hasn't been updated on the nek5000 website here: https://nek5000.mcs.anl.gov/documentation/

**Comment by stgeke** [comment]
I think this should go to the nekdoc repository.

**Comment by lcarasik** [comment]
Understood. Thanks!

**Comment by RonRahaman** [comment]
Hey @lcarasik, thanks for fixing this in Nek5000/NekDoc/#8.  hough it looks like the

**Comment by RonRahaman** [comment]
Hey @lcarasik, thanks for fixing this in NekDoc.  To update the [HTML](http://nek5000.github.io/NekDoc/Nek_users.html) and [PDF](http://nek5000.github.io/NekDoc/Nek_users.pdf) docs, a member of the Nek5000 [Documenters](https://github.com/orgs/Nek5000/teams/documenters) team must checkout the NekDoc repo and run the 'make gh-pages' target.  

I just did this.  Could you confirm that your changes appear on the website?  If so, we can close this issue again.

**Comment by lcarasik** [comment]
They are corrected! Sorry for my inexperience!

**Comment by RonRahaman** [comment]
No worries, it a pretty obscure workflow.  :)

**Comment by msaikat6** [comment]
Hello everyone,

Just as an update, this issue still hasn't been fixed. The documentation still has the definitions of udiff and utrans flipped.

Thanks,
Saikat
