### ISSUE TITLE
Code does not compile on BG/Q with the PPLIST="BGQ" flag

### ISSUE THREAD

**Issue by ggiannako** [Nek5000/Nek5000#47]
The code does not compile on the BGQ with the PPLIST="BGQ" flag.
The mxm_wrapper.f and mxm_bgq.f contain f90 syntax. The code cannot compile neither with mpixlf90 nor with mpixlf77.

Even if the syntax in mxm_wrapper.f and mxm_bgq.f is converted to f77, we get “undefined references” to some blas routines at compile time.
The problem is not fixed either with the BLAS_MXM flag of PPLIST.

Are there any other flags that should be used along with "BGQ"?
If yes, it would be good to have it documented.

**Comment by stgeke** [comment]
Yes, this needs to be fixed. For now, just do:
- [ ] Make mxm_wrapper.f conform to F77
- [ ] Change mxm_bgq.f from free to fixed format
- [ ] Add `blas.o` to `MXM_USER`

**Comment by maxhutch** [comment]
PPLIST=`BGQ` isn't necessary to build on BGQ, so you can just take it out of the PPLIST.  I"ll fix these issues.

**Comment by maxhutch** [comment]
@ggiannako : I think that I fixed it with #48 .  Can you test it out:

```
git clone -b bugfix-47 https://github.com/maxhutch/nek5000.git
```

**Comment by stgeke** [comment]
This change does not make the code F77 compliant.

**Comment by ggiannako** [comment]
I know the code works without the PPLIST=BGQ flag, but one would want to benefit from the BGQ-specific mxm's...

However, the problem is not fixed with #48. 
Only when all the changes suggested by @stgeke are made the code compiles and runs fine.

**Comment by maxhutch** [comment]
I'm bad and I feel bad...

Try again?

**Comment by stgeke** [comment]
The code is still not F77 compliant as it is using free text format.
